---
title: "Dr. Lump and Dr. Split duke it out"
author: "Roger Day"
date: \"`r date()`
output: 
  html_notebook: 
    number_sections: yes
runtime: shiny
---

NAVIGATE:

Top of the [Notebook](#notebook) .

Let's run some code.



```{r}
cat('hello everybody\n')
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
logit = function(p) log(p/(1-p))
antilogit = function(x) 1 - 1/(1+exp(x))
DLdata = matrix(c(3,5,2,90),nrow=2)
dimnames(DLdata) = list(c("D","L"),c("R","N"))
ColorForPrior="green";     
ColorForPosterior="red";     
ColorForLikelihood="black"

source("Plight-Pdark-posterior-new.R", local=TRUE)

rValues = reactiveValues(tau = 1,  phi = 0.001, mu=0.5,
                         title_1='title 1',
                         DLdata = DLdata)

plotPlightPdarkPosteriorReactive = reactive( {
  cat("PLOTTING   ")
  tau <- input$tauInput
  phi <- input$phiInput
  mu0 <- input$mu0Input
  cat("tau=", tau, " phi=", phi, " mu0=", mu0, "\n")
  plotPlightPdarkPosterior(DLdata=rValues$DLdata,
                           tau=tau, phi=phi, mu0=logit(mu0), 
                           showPrior = input$checkPrior, 
                           showPosterior = input$checkPosterior,
                           fudgeFactor = input$fudgeFactor)
  rValues$title_3 <<- paste0(
    "  tau=", input$tauInput,  
    ",  phi=", input$phiInput,  
    ",  mu0=", input$mu0Input 
  )
})
lumpReact = observe({
  if(length(input$lumpID) > 0) {
    cat("lumpID\n")
    rValues$tau <- 1; rValues$phi <- 0.001   
    ### Lump:  no individual variation:   D is same as L.
    rValues$title_1 <- "Lump"
    rValues$title_2 <- "Prior belief:  P dark = P light "
  }
})  

updateDLdata = observe({
  try({
    rValues$DLdata[1,1] = input$mRD
    rValues$DLdata[1,2] = input$mND
    rValues$DLdata[2,1] = input$mRL
    rValues$DLdata[2,2] = input$mNL
  })
  cat('input$mRD', input$mRD, '\n')
})

splitReact = observe({
  if(length(input$splitID) > 0) {
    cat("splitID\n")
    rValues$tau <<- 0; rValues$phi <<- 1   
    ### Split:  D unconnected to L.
    rValues$title_1 <<- "Split"
    rValues$title_2 <<- " P dark and P light are unrelated"
  }
}) 
mixedReact = observe({
  if(length(input$mixedID) > 0) {
    cat("mixedID\n")
    rValues$tau <<- 1/2; rValues$phi <<- 1/2 
    rValues$title_1 <<- "Compromise: lump some, split some"
    rValues$title_2 <<- "Prior belief:  P dark is somewhat related to P light. "
  }
})

updateViews = observe({
  updateNumericInput(session=session, inputId="tauInput", 
                     value = rValues$tau)
  updateNumericInput(session=session, inputId="phiInput", 
                     value = rValues$phi)
})

output$title_1_ID = renderText({rValues$title_1})
output$title_2_ID = renderText({rValues$title_2})
output$title_3_ID = renderText({rValues$title_3})

output$thePlot = renderPlot(width=500, height=500,
                            {
                              par(mai=c(1.4,1.4,1.1,0.6))
                              par(mar=c(5,5,4,2) + 0.2)
                              plotPlightPdarkPosteriorReactive()
                            })

output$responseRates = renderText({
  paste(input$mRD, '/', input$mRD+input$mND, "for D, and ",
        input$mRL, '/', input$mRL+input$mNL, "for L.")
})
```

```{r}
##### UI components #####
#### notebookColumn ####  
notebookColumn =   
  column(width = 4, 
         h1("Notebook"),
         wellPanel(
           strong(pre(
             'Goal: decide whather to treat "D" patients.',
             'We set the Bayesian joint prior, and compute the joint posterior.',
             '(This bivariate normal approximation on the logit scales is pretty good,',
             'except at or near zero counts. )')),
           h2("Lumping the groups"),
           h2("Splitting the groups")
         ))
```
```{r}
#### UI fluidPage####
fluidPage(
  title  = 'Bias-variance-smoothing-shrinking', 
  # Application title
  titlePanel("Bias-variance-smoothing-shrinking"),
  
  notebookColumn,
  
  column(width = 8, 
         h1("Response by Predictor"),
         h2("Data"),
         splitLayout("", "Responders", "non-responders"),
         splitLayout("Group 'L'",
                     numericInput('mRL', 'mRL', DLdata[2,1]),
                     numericInput('mNL', 'mNL', DLdata[2,2])
         ),
         splitLayout( "Group 'D'",
                      numericInput('mRD', 'mRD', DLdata[1,1]),
                      numericInput('mND', 'mND', DLdata[1,2])
         ), 
         
         br()
  ),
  sidebarLayout(sidebarPanel = 
                  sidebarPanel(
                    wellPanel(
                      
                      wellPanel(
                        numericInput("phiInput", "prior variance | group (phi)", 
                                     value=0, min = 0.00, step=0.1),
                        numericInput("tauInput", "shared additional variance (tau)", 
                                     value=1, min = 0.00, step=0.1),
                        numericInput("mu0Input", "shared prior mean", 
                                     value=0.5, min = 0.001, step=0.1, max=0.999),
                        actionButton("lumpID", label = "Lump"),
                        actionButton("splitID", label = "Split"),
                        actionButton("mixedID", label = "Mixed")
                      ),
                      "X = observed response rate, ",
                      br(),
                      textOutput(outputId = 'responseRates'),
                      numericInput(inputId = 'fudgeFactor', label = 'continuity fudge factor', value=1),
                      div(style="color:green", 
                          checkboxInput("checkPrior", 
                                        "Green = prior distribution",
                                        TRUE)),
                      div(style="color:red",
                          checkboxInput("checkPosterior", 
                                        "Red = posterior distribution",
                                        TRUE)),
                      "Shaded: 50% highest posterior region"
                    )
                  )
                ,
                mainPanel = mainPanel(
                  
                  br(),
                  tagAppendAttributes(
                    div(
                      textOutput(outputId="title_1_ID"),
                      textOutput(outputId="title_2_ID"),
                      textOutput(outputId="title_3_ID")
                    ),
                    style=
                      'text-align:center; font-size:large; font-weight:bold'),
                  plotOutput(outputId = 'thePlot')
                )
  )
)


```
  
  
  