---
output: html_document
runtime: shiny
---

<!-- 
To Deploy: 
Click Run document, then in upper right: "Republish"
Or, 
rsconnect::deployApp(appFiles = 
c('simplebayesdecision-fancy.Rmd', 'inclRmd.R',
'conditionalPanelWithCheckbox.R','addOpacity.R',
'simplebayesdecision-info.Rmd', "simplebayesdecision.R" 
, "gerdPlot.R" 
, "gerdPlot2.R"  )) 
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{css}
  .myTable th {
    padding: 30px;
  }
  h3 {
   color: #00a400;;
  }
  h4 {
   color: #a40;;
  }
  wellPanel {padding: 30px !important;}
  
  .shiny-input-radiogroup label {
  display: inline-block;
  text-align: center;
  }
  .shiny-input-radiogroup label input[type='radio'] {
  display: block;
  margin: 2em auto;
  }
  
```
  
```{r, echo=F}
usingShinyApp = FALSE
temp = suppressPackageStartupMessages(require('shinyjs', quietly=TRUE))
temp = suppressPackageStartupMessages(require('markdown', quietly=TRUE))

source("inclRmd.R")
source("conditionalPanelWithCheckbox.R")
source("addOpacity.R")
source("makePosteriorSequence.R")


```

```{r}
priorDefaults = 
  c(prior_dD=0.009, prior_hD=0.001, prior_iD=0.09, prior_noD=0.9)
prob_pos_Defaults = 
  c(prob_pos_dD=0.9, prob_pos_hD=0.1, prob_pos_iD=0.9, prob_pos_noD=0.1)


output$priorUI = renderUI(
  {
    div(
      h4(style='text-align:center', "Initial (prior) probabilities"),
      fluidRow(
        splitLayout(
          numericInput(
            'prior_dD',
            ('detectable D') ,
            value = priorDefaults['prior_dD'],
            min = 0, max=1, step = 0.01),
          numericInput('prior_hD',
                       ('hidden D'),
                       value = priorDefaults['prior_hD'],
                       min = 0, max=1, step = 0.01),
          numericInput('prior_iD',
                       ('imposter D'),
                       value = priorDefaults['prior_iD'],
                       min = 0, max=1, step = 0.01),
          numericInput('prior_noD',  
                       ('no D'),
                       value = priorDefaults['prior_noD'],
                       min = 0, max=1, step = 0.01)
        )))
    
  }
)
# library(shinyWidgets)
WIDE = function(x) x
WIDE = function(x) (paste0('', x, 
                           paste(collapse='', rep('.', 0))))
output$whichFollows = renderUI(
  div(
          h4(style='text-align:center', 
             "Probabilities add to one. This one adjusts to the other 3."),
  fluidRow(column(12, offset=0,
                  radioButtons(inputId = 'whichFollows', 
                      choiceNames = 
#            c(WIDE('dD'), WIDE('hD'), WIDE('iD'), WIDE('noD')), 
  c(WIDE('detectable D'), WIDE('hidden D'), WIDE('imposter D'), WIDE('no Disease')),
                      choiceValues = 
              c('dD', 'hD', 'iD', 'noD'),
            label='',
                               selected='noD', width='100%', #class='btn-block',
               inline=T))
)))


output$prob_pos_UI = renderUI(
  {
    div(
      h4(style='text-align:center', "Probabilities of a positive"),
      fluidRow(
        splitLayout(
          numericInput(
            'prob_pos_dD',
            ('detectable D') ,
            value = prob_pos_Defaults['prob_pos_dD'],
            min = 0, max=1, step = 0.01),
          numericInput('prob_pos_hD',
                       ('hidden D'),
                       value = prob_pos_Defaults['prob_pos_hD'],
                       min = 0, max=1, step = 0.01),
          numericInput('prob_pos_iD',
                       ('imposter D'),
                       value = prob_pos_Defaults['prob_pos_iD'],
                       min = 0, max=1, step = 0.01),
          numericInput('prob_pos_noD',  
                       ('no D'),
                       value = prob_pos_Defaults['prob_pos_noD'],
                       min = 0, max=1, step = 0.01)
        )))
    
  }
)
output$ObservationUI = 
  renderUI(
    div(style='text-align:center',
        h4(style='text-align:center', "Data reports"),
        fluidRow(style='text-align:center',
            column(12, textInput(width = '400px',
                      "dataInputID",
                      value = "1 1 1 1",
                      label=HTML("Test results (1s and 2s, format like 1 2 1 2)"),
            )))
  ))
```

```{r}

ui = 
  fillPage(  #fillPage and fluidPage the same.
    useShinyjs(rmd=TRUE, debug=TRUE),  ## this is the place!!
    tags$head(
        tags$style(HTML("
            .shiny-input-radiogroup label {
                display: inline-block;
                text-align: center;
            }
            .shiny-input-radiogroup label input[type='radio'] {
                display: block;
                margin: 2em auto;
            }

        "))
    ),
    h3("Conditional dependence in medical diagnosis"),
    fluidRow(
      column(7, #wellPanel
             uiOutput('priorUI'), 
             uiOutput('whichFollows'),
             hr(),
             uiOutput('ObservationUI'), 
             uiOutput('prob_pos_UI'), 
      ),
      column(5,
             #https://stackoverflow.com/questions/51460955/how-to-make-kable-table-reactive-in-shiny-app-shiny-kable
             br(),br(),br(),br(),br(),
             h4("Results: posterior probabilities"),
             htmlOutput('makePosteriorSequence'))
    )
  )


```

```{r}
####  server ####

server = function(input, output) {
  observeEvent( 
    c(input$prior_dD, input$prior_dD, input$prior_iD, input$prior_noD ),
    {
  #radio
      switch(gsub('_', '', input$whichFollows),
             hD= updateNumericInput(
               inputId='prior_hD', value = 1 - 
                 input$prior_dD-input$prior_iD-input$prior_noD),
             dD=updateNumericInput(
               inputId='prior_dD', value = 1 - 
                 input$prior_hD - input$prior_iD - input$prior_noD),
             iD=updateNumericInput(
               inputId='prior_iD', value = 1 - 
                 input$prior_dD - input$prior_hD - input$prior_noD),
             noD=updateNumericInput(
               inputId='prior_noD', value = 1 - 
                 input$prior_dD - input$prior_iD - input$prior_hD)
      )
    }
  )
  


  output$makePosteriorSequence = renderText({
    req(input$dataInputID)
    # req(input$prior_dD, input$prior_hD, input$prior_iD, input$prior_noD) ### causes it to break
    req(abs(input$prior_dD+input$prior_hD+input$prior_iD
            + input$prior_noD -  1.00)  < 1e-7)
      # this doesn't prevent the "cat" below, but ok.
    req(c(input$prob_pos_dD, input$prob_pos_hD, 
          input$prob_pos_iD, input$prob_pos_noD))
    this_priorFor4 = 
      c(input$prior_dD, input$prior_hD, 
        input$prior_iD, input$prior_noD)
    this_prob_pos_given_group = c(
      input$prob_pos_dD, input$prob_pos_hD, 
      input$prob_pos_iD, input$prob_pos_noD)
    cat('this_priorFor4', this_priorFor4, '\n')
    cat('this_prob_pos_given_group', this_prob_pos_given_group, '\n')
    dataSequence = strsplit(split=' ',
                            input$dataInputID)[[1]]
    dataSequence = sapply(dataSequence, as.numeric)
    print(dataSequence)
    ## only 1's and 2's
    #dataSequence <<- rep(1,4)
    if(all(dataSequence %in% 1:2)) { #proceed
      #run_makePosteriorSequence()
      #posteriorSequenceOutput ( 
      (
        makePosteriorSequence(
          priorFor4 = this_priorFor4,
          prob_pos_given_group = this_prob_pos_given_group,
          dataSequence = dataSequence, ### 1's and 2's
          #wordsForData = c("'Pos'\\quad", "'Neg'\\quad"),
          dropZeroGroups = FALSE,
          makeHTML = TRUE, 
          marginalize = FALSE # input$marginalize
        ) ) 
    } ### end, call to makePosteriorSequence
  })  ### end, renderText 
}  ## end, server


if(usingShinyApp) {
  shinyApp(ui = ui, server = server)
} else {
  server(input, output)
  ui
}


```

