---
title: "Conditional dependence in medical diagnosis"
output: html_document
runtime: shiny
---

<!-- 
To Deploy: 
Click Run document, then in upper right: "Republish"
Or, 
rsconnect::deployApp(appFiles = 
c('simplebayesdecision-fancy.Rmd', 'inclRmd.R',
'conditionalPanelWithCheckbox.R','addOpacity.R',
'simplebayesdecision-info.Rmd', "simplebayesdecision.R" 
, "gerdPlot.R" 
, "gerdPlot2.R"  )) 
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=F}
usingShinyApp = FALSE
temp = suppressPackageStartupMessages(require('shinyjs', quietly=TRUE))
temp = suppressPackageStartupMessages(require('markdown', quietly=TRUE))

source("inclRmd.R")
source("conditionalPanelWithCheckbox.R")
source("addOpacity.R")
source("makePosteriorSequence.R")


```

```{r}
priorDefaults = 
  c(pr_dD=0.009, pr_hD=0.001, pr_iD=0.09, pr_noD=0.9)


rV= reactiveValues(
  priors = priorDefaults
)  

observeEvent( input$pr_dD, {
  # priors = isolate(rV$priors)
  # priors$pr_dD = input$pr_dD
  # rV$priors = priors
  print(rV$priors)
}
)
#         {
#           rV$priors =
#           c(pr_dD=input$pr_dD, pr_hD=input$pr_hD,
#             pr_iD=input$pr_iD, pr_noD=input$pr_noD)
# })

output$parameterUI = renderUI(
  {
    div(
      h3(style='text-align:center', "Initial (prior) probabilities"),
      fluidRow(
        splitLayout(
          numericInput(
            'pr_dD',
            ('detectable D') ,
            value = priorDefaults['pr_dD'],
            min = 0, max=1, step = 0.01),
          numericInput('pr_hD',
                       ('hidden D'),
                       value = priorDefaults['pr_hD'],
                       min = 0, max=1, step = 0.01),
          numericInput('pr_iD',
                       ('imposter D'),
                       value = priorDefaults['pr_iD'],
                       min = 0, max=1, step = 0.01),
          numericInput('pr_noD',  
                       ### best to slave this one for now.
                       ('no D'),
                       value = priorDefaults['pr_noD'],
                       min = 0, max=1, step = 0.01)
        )))
    
  }
)

output$ObservationUI = 
  renderUI(
    div(
        textInput(
          "dataInputID",
          value = "1 1 1 1",
          label=HTML("Test results (1s and 2s, format like 1 2 1 2)"),
        ))
  )
```

```{r}

ui = 
  fillPage(  #fillPage and fluidPage the same.
    useShinyjs(rmd=TRUE, debug=TRUE),  ## this is the place!!
    fluidRow(
      column(12,   uiOutput('parameterUI')), 
      column(12,   uiOutput('ObservationUI')), 
      #https://stackoverflow.com/questions/51460955/how-to-make-kable-table-reactive-in-shiny-app-shiny-kable
      column(12,   htmlOutput('makePosteriorSequence')),
      column(12,   'all done!')
    )
  )

```

```{r}
####  server ####

server = function(input, output) {
  
  #rV = reactiveValues(prior=c())
  # posteriorSequenceOutput =
  #   reactiveVal('posteriorSequenceOutput')
  
  run_makePosteriorSequence = function() {
    # TODO, maybe
  }
  output$makePosteriorSequence = renderText({
    req(input$dataInputID)
    req(rV$priors)
    dataSequence = strsplit(split=' ',
                            input$dataInputID)[[1]]
    dataSequence = sapply(dataSequence, as.numeric)
    print(dataSequence)
    ## only 1's and 2's
    #dataSequence <<- rep(1,4)
    if(all(dataSequence %in% 1:2)) { #proceed
      #run_makePosteriorSequence()
      #posteriorSequenceOutput ( 
      (
        makePosteriorSequence(
          priorFor4 = rV$priors,
          pr_pos_given_group = c(1, 0, 1, 0),
          dataSequence = dataSequence, ### 1's and 2's
          wordsForData = c("'Pos'\\quad", "'Neg'\\quad"),
          dropZeroGroups = FALSE,
          makeHTML = TRUE, 
          marginalize = FALSE # input$marginalize
        ) ) 
    } ### end, call to makePosteriorSequence
  })  ### end, renderText 
}  ## end, server


if(usingShinyApp) {
  shinyApp(ui = ui, server = server)
} else {
  server(input, output)
  ui
}


```

