---
title: "Bayes expected loss for making medical decisions"
output: html_document
author: Statistics Beautiful, `r Sys.Date()`
runtime: shiny
---



```{r, echo=F}
usingShinyApp = FALSE
temp = suppressPackageStartupMessages(require('shinyjs', quietly=TRUE))
temp = suppressPackageStartupMessages(require('markdown', quietly=TRUE))

source("inclRmd.R")
source("conditionalPanelWithCheckbox.R")
source("addOpacity.R")


```


```{r, echo=FALSE}


#### predictiveValueDisplay ####
predictiveValueDisplay = list(
  h3(style='text-align:center', 'Predictive values'),
  wellPanel(fluidRow(
    column(6, span(strong(
      "\"Positive P.V.\"",br(),
      "Pr(Sick given Positive)",
      em(textOutput('predValuePos'))))
    ),
    column(6, span(strong(
      "\"Negative P.V.\"", br(),
      "Pr(Healthy given Negative)",
      em(textOutput('predValueNeg'))))
))))


#### odds_display ####
mathOp = function(s)
  span(style='color: blue',
       strong(
        HTML(paste0('<br><br>',s))
  ))
odds_display = list(
  h3(style='text-align:center', 'Odds'),
  wellPanel(fluidRow(
    column(2
      , 
      span(strong(
        HTML("Prior <br>odds"),
             em(textOutput('priorOdds')))) ),
    column(1, mathOp('X')),
    column(
      3,
      span(strong(
        HTML("Likelihood <br>ratio"),
        em(textOutput('likelihoodRatio')))) ),
    column(1, mathOp("=")),
    column(
      5,
      span(strong( 
                  textOutput(
                    'posteriorOddsLabel'),
                  em(textOutput('postOdds'))))
    )
  )))

#### controls ####

controls <<- list(
    uiOutput('parameterUI')
)

#### Odds_and_predictive_values ####
Odds_and_predictive_values = list(
  fluidRow(
    column(
      6,
      (predictiveValueDisplay)
    ),
    column(
      6,
      (odds_display)
    )
  )
)
 

####  server ####

server = function(input, output) {
source("simplebayesdecision.R")
source("gerdPlot.R")
source("gerdPlot2.R")



f_which.varies = function()
  names(longparamnames)[
    which(input$parameterInputID ==
            longparamnames)]

#border-left:3px dashed;

dashWrap = function(s)
             HTML(paste0(
                  "<div style = 'color: blue;
                  font-weight:strong';",
                  "font-style: italic;>",
                  "∎", s
                   , "</div>"
                  ) )
DashedLine = ## NOT USED
"
            border-color:  rgba(0, 100, 200, 1);
color: rgba(0, 100, 200, 1); 
font-weight: bold; 
background-color: rgba(200, 100, 0, 1)
"

longparamnames = c(prev="prevalence", 
                   sens="sensitivity",
                   spec="specificity",
               L.SW="Loss_given_S_and_W",
               L.HT="Loss_given_H_and_T")
paramArgDefaults = unlist(formals(plot.simple.bayes)[1:5])
###  a few alterations...
paramArgDefaults['prev'] = 0.01
paramArgDefaults['sens'] = 0.90
paramArgDefaults['spec'] = 0.91

paramArgNames = names(paramArgDefaults)
paramPlotRange = 
  paramPlotRangeDefaults = 
  c(
    prev='seq(0.0, 0.2, by=0.01)',
    sens='seq(0.5,1,.05)',
    spec='seq(0.9,1,.01)',
    L.SW='seq(0.5,10,0.5)',
    L.HT='seq(0.5,10,0.5)')

observeEvent(input$rangeInputID, {
  paramPlotRange[[f_which.varies()]] <<- input$rangeInputID
  #might not be needed
})
setJSdefaultsAttribute = 
  function(param, att, value, parent=FALSE) {
    thisId = paste0(param, 'Default')
    jsString = paste0(
      "document.getElementById('",
      thisId, "')", ifelse(parent, ".parentElement", ""),
      ".style.", att, " = '", value, "'")
    #cat('jsString :', jsString, '\n')
    shinyjs::runjs(jsString)
  }
observeEvent(
  input$parameterInputID,
  {
    namesForNumericInputs = list(
      sens='sensitivity',
      spec='specificity',
      prev='prevalence',
      L.SW = 'Loss<br>Sick&Wait',
      L.HT = 'Loss<br>Healthy&Treat'
    )
    for(param in paramArgNames) {
#      str = namesForNumericInputs[[param]]
      theColor = ifelse( 
        param == f_which.varies(), 
        'blue', 'black')
      setJSdefaultsAttribute(param, 
                             'color', theColor)
      setJSdefaultsAttribute(param, 
                             'color', theColor,
                             parent=TRUE)
      fontStyle = ifelse( 
        param == f_which.varies(), 
         'oblique', 'normal')
      setJSdefaultsAttribute(param, 
                             'fontStyle',
                             fontStyle,
                             parent=TRUE)
    }
    ### now, updating the rangeInputID
    updateTextInput(inputId='rangeInputID',
                    value=paramPlotRange[[
                      f_which.varies()]])
})

output$parameterUI = renderUI(
  {
    probParamUI = div(
      h3(style='text-align:center', "Probabilities"),
      fluidRow(
        splitLayout(
          numericInput(
            'prevDefault',
            ('prevalence') ,
            value = paramArgDefaults['prev'],
            min = 0, max=1, step = 0.01),
          numericInput('sensDefault',
                       ('sensitivity'),
                       value = paramArgDefaults['sens'],
                       min = 0, max=1, step = 0.01),
          numericInput('specDefault',
                       ('specificity'),
                       value = paramArgDefaults['spec'],
                       min = 0, max=1, step = 0.01)
    )))
  LossesUI = 
    div( #h5(style='text-align:center', "Losses & axis"),
    fluidRow(
      column(1, ""),
    column(5, numericInput('L.SWDefault',
                 HTML('Loss if Sick&Wait'),
                 value = paramArgDefaults['L.SW'],
                 min = 0, max=10, step = 0.1, width='100%')),
    column(5, numericInput('L.HTDefault',
                 HTML('Loss if Healthy&Treat'),
                 value = paramArgDefaults['L.HT'],
                 min = 0, max=10, step = 0.1, width='100%'))
    ))
  ObservationUI = 
    selectInput(
      "dataInputID",
      label=HTML("Observation<br> (test)"),
      choices = c("Positive","Negative"),
      selected="Positive",
      selectize=FALSE)
  
  
  axisUI = div(
    fluidRow(
    column(6, 
           selectInput("parameterInputID", 
                       label = dashWrap('horizontal axis'),
                       choices = as.vector(longparamnames), 
                       selected = as.vector(longparamnames[1]),
                       selectize=FALSE)
    ),
   column(6, 
           textInput('rangeInputID',
                       label = dashWrap('horizontal axis points'),
                   value = paramPlotRange['prev']),
    )
    )
  )
  
  div(
    conditionalPanel('input.plotChoice != "1"',
                     HTML(paste0(rep('<br>', 13)))
    ),
    conditionalPanel('input.plotChoice === "1"', 
                     wellPanel(
                       div(LossesUI, hr(), axisUI), 
                       style = "padding-bottom: 1px;
                       padding-top: -10px;"
    )),
    wellPanel(probParamUI, 
              style = "padding-bottom: 1px;padding-top: 1px;
              padding-right: 25px;"),
    ObservationUI
    )  
  }
)

output$posteriorOddsLabel = renderText(
  paste("Posterior odds ", "given test = ", input$dataInputID))

output$priorOdds = renderText(
  as.character(signif(
    digits=2,
    input$prevDefault /
      (1-input$prevDefault)
  ))
)

LikRat = reactive( {
  if(is.null(input$dataInputID)) return(NA)
  value = try(switch(EXPR = 
    input$dataInputID,
    Positive = 
      input$sensDefault / 
      (1 - input$specDefault),
    Negative = 
      (1-input$sensDefault) /
      input$specDefault)
  )
  if(class(value)== 'try-error') value = NA
  value
})
output$likelihoodRatio = renderText( {
  as.character(
    signif(digits=2, LikRat()
  ))
})
output$postOdds = renderText( {
  priorOdds = input$prevDefault /
    (1-input$prevDefault) 
  postOdds = priorOdds * LikRat()
  as.character(
    signif(digits=2, postOdds
  ))
  })
output$predValuePos = renderText({
  prev = input$prevDefault
  sens = input$sensDefault
  spec = input$specDefault
  signif(digits=3,
         prev * sens / (prev * sens + (1-prev)*(1-spec))
  )
})
output$predValueNeg = renderText({
  prev = input$prevDefault
  sens = input$sensDefault
  spec = input$specDefault
  signif(digits=3,
         (1-prev) * spec / ((1-prev) * spec + prev*(1-sens))
)
})
    
output$thePlot = renderPlot({
  input$rangeInputID  ## to incur a reactivity
  ## First, set all parameters to their defaults.
  paramArgDefaults['prev'] = input$prevDefault
  paramArgDefaults['sens'] = input$sensDefault
  paramArgDefaults['spec'] = input$specDefault
  paramArgDefaults['L.SW'] = input$L.SWDefault
  paramArgDefaults['L.HT'] = input$L.HTDefault
  sapply(paramArgNames, function(param) 
    assign(param, paramArgDefaults[param], envir=.GlobalEnv))
  assign('paramPlotRange', paramPlotRange, envir=.GlobalEnv)
  ### Here pos=1 is the same as env=.GlobalEnv -- try search().
  ### Now, swap in the vector for the selected parameter.
  cat(f_which.varies(), '- ',
      longparamnames[f_which.varies()], "--  ",
       "\n")
  horiz.label = input$parameterInputID 
  horiz.values = eval(parse(text=input$rangeInputID))
  
  #Save the default value, and reassign the vector of values
  default.value = paramArgDefaults[f_which.varies()]
  # You need to use "assign"; we can't hard-code the variable name.
  cat ('paramArgNames \n')
  print(paramArgNames)
  cat('longparamnames', '\n')
  print(longparamnames)
         assign(f_which.varies(),
         horiz.values)
  E.loss = simple.bayes.vectorized(
    prev, sens, spec, L.SW, L.HT, 
    substr(input$dataInputID, 1, 1) )
  E.loss.W = E.loss[ , 1]
  E.loss.T = E.loss[ , 2]
  #https://stackoverflow.com/questions/3778084/how-to-adjust-the-size-of-y-axis-labels-only-in-r
  plot(cex.axis=2, cex.lab=1.8,
    c(horiz.values, horiz.values), 
    c(E.loss.T, E.loss.W), 
    pch=" ",
    ylab="Bayes expected loss",
    xlab=input$parameterInputID,
    main=paste(
      "X = ", input$dataInputID,
      "   Varying ", input$parameterInputID))
  Wbetter = (E.loss.W < E.loss.T - 1e-2) 
  Tbetter = (E.loss.W > E.loss.T + 1e-2) 
  WbetterPlusOne = 1 + (E.loss.W < E.loss.T) 
  TbetterPlusOne = 1 + (E.loss.W > E.loss.T) 
  colorW = c('red', 'darkgreen')[WbetterPlusOne]
  colorT = c('red', 'darkgreen')[TbetterPlusOne]
  colorT[!(Wbetter | Tbetter)] = 
    colorW[!(Wbetter | Tbetter)] = 'blue'
  cexT = c(1,4)[TbetterPlusOne]
  cexW = c(1,4)[WbetterPlusOne]
  cexT[!(Wbetter | Tbetter)] = 
    cexW[!(Wbetter | Tbetter)] = 0
  points(horiz.values, E.loss.W, pch= "W",
         col=colorW, cex=cexW)
  points(horiz.values, E.loss.T, pch= "T",
         col=colorT, cex=cexT)
  abline(v=default.value, lty=3, lwd=10, col="blue")

  })
  output$gerdUI = 
    renderUI({
    cat('gerdUI, plotChoice = ', input$plotChoice, '\n')
      div(
        conditionalPanel(condition = 'input.plotChoice === "1"', {
                    div( h3(style='text-align:center; color:green',
                        HTML('Best action is in GREEN')),
                         plotOutput('thePlot') ) }),
        conditionalPanel(condition = 'input.plotChoice === "2"',
                         plotOutput('gerdPlot') ),
        conditionalPanel(condition = 'input.plotChoice === "3"',
                         plotOutput('gerdPlot2') ),
        conditionalPanel(condition = 'input.plotChoice === "0"',
                         plotOutput('happyImage') ),
       )
  })
  output$gerdPlot =
    renderPlot({
    gerdPlot(sens = input$sensDefault,
             spec = input$specDefault,
             prev = input$prevDefault)
  })
  output$gerdPlot2 =
    renderPlot({
    gerdPlot2(sens = input$sensDefault,
             spec = input$specDefault,
             prev = input$prevDefault)
  })
  output$happyImage = 
    renderPlot({
      par(oma=c(0,0,0,0))
      par(mai=c(0,0,1,0))
      N = 1000
      Ylevels = c(1.05, 0.8, 0.5, 0.3)
      text_for_treeNumber = function(x, y, NNN, CEX=1.5){
              text(x, y, NNN, xpd=NA, cex=CEX,
                   col='darkgreen',
                   vfont = c('serif', 'bold'))
      } 
      plot(0:1, 0:1, axes=F, pch='')
      title('Natural counts')
      text_for_treeNumber(0.5, Ylevels[1], N)
      text(0.5, Ylevels[1] - 0.05 , 'people tested', xpd=NA)
      Sick = round(N * input$prevDefault)
      text_for_treeNumber(0.3, Ylevels[2] , Sick)
      text(0.3, Ylevels[2] - 0.05 , '\"Sick\"')
      text(x = 0.375, y=(Ylevels[1]- 0.1 + Ylevels[2]+ 0.05)/2,
           'prevalence', col='blue', cex=1.5)
      arrows(x0 = 0.4, x1 = 0.31, y0=Ylevels[1]- 0.1, y1=Ylevels[2]+ 0.03, lwd = 3)
      NotSick =  N - Sick
      text_for_treeNumber(0.7, Ylevels[2] , NotSick)
      text(0.7, Ylevels[2] - 0.05 , 'not \"Sick\"')
      arrows(x0 = 0.6, x1 = 0.69, y0=Ylevels[1]- 0.1, y1=Ylevels[2]+ 0.03, lwd = 3)
      TP = round(Sick * input$sensDefault)
      text_for_treeNumber(0.2, Ylevels[3] , TP)
      text(0.2, Ylevels[3] - 0.05, 'true positive')
      text(x = 0.25, y=(Ylevels[2]- 0.1 + Ylevels[3]+ 0.05)/2,
           'sensitivity', col='blue', cex=1)
      arrows(x0 = 0.27, x1 = 0.22, y0=Ylevels[2]-0.1, y1=Ylevels[3]+0.05, lwd=3)
      FN = round(Sick - TP)
      text_for_treeNumber(0.4, Ylevels[3] , FN)
      text(0.4, Ylevels[3] - 0.05, 'false negative')
      arrows(x0 = 0.33, x1 = 0.38, y0=Ylevels[2]-0.1, y1=Ylevels[3]+0.05, lwd=3)

      TN = round(NotSick * input$specDefault)
      FP = round(NotSick - TN)
      text_for_treeNumber(0.8, Ylevels[3] , FP)
      text(0.8, Ylevels[3] - 0.05, 'false positive')
      arrows(x0 = 0.73, x1 = 0.78, y0=Ylevels[2]-0.1, y1=Ylevels[3]+0.05, lwd=3)
      FN = round(NotSick - TP)
      text_for_treeNumber(0.6, Ylevels[3] , FN)
      text(0.6, Ylevels[3] - 0.05, 'true negative')
      text(x = 1-0.35, y=(Ylevels[2]- 0.1 + Ylevels[3]+ 0.05)/2,
           'specificity', col='blue', cex=1)
      arrows(x0 = 1-0.33, x1 = 1-0.38, y0=Ylevels[2]-0.1, y1=Ylevels[3]+0.05, lwd=3)

      text_for_treeNumber(0.5, Ylevels[4], TP)
      text(0.5, Ylevels[4] - 0.03, '___')
      text_for_treeNumber(0.5, Ylevels[4] - 0.06, paste0(TP, "+", FP))
      text_for_treeNumber(
        0.5, Ylevels[4] - 0.12, 
        paste0('= ', round(digits=3, TP/(TP+FP))))
      text(0.5, Ylevels[4] - 0.2, 
           cex=1.5,
           'So the chance the person is "Sick" if test is positive equals ')
      text_for_treeNumber(0.5, Ylevels[4] - 0.28, 
           CEX=2.5,
           round(digits=3, TP/(TP+FP)))
      arrows(x0 = 1-0.78, x1 = 1-0.58, y0=Ylevels[3]-0.1, y1=Ylevels[4]-0.05, lwd=3)
      arrows(x0 = 0.78, x1 = 0.58, y0=Ylevels[3]-0.1, y1=Ylevels[4]-0.05, lwd=3)

    })  ### end of happy face
  
  cbStringId = 'topicId'
  output$topicId  <- renderUI({
    span(
      checkboxInput(cbStringId,
                    strong(em(showhideString('details', FALSE)
                    )),
                    value=FALSE),
      conditionalPanel(
        condition = paste0('input.', cbStringId),
        wellPanel(
          inclRmd(
            'simplebayesdecision-info.Rmd'
          )  )
      )
      #### HERE ####
    )  })

  observeEvent(
    input[[cbStringId]], {
      fullString = showhideString('details', input[[cbStringId]])
      updateCheckboxInput(
        session, cbStringId,
        label=fullString)
    }
  )

}   #### End of server ####

#### UI ####
ui = 
fluidPage(
  useShinyjs(rmd=TRUE, debug=TRUE),  ## this is the place!!
  uiOutput('topicId'),
  fluidRow(
    column(6, 
           div(style="color:red;",
               radioButtons('plotChoice', 
                            label='', choiceValues=0:3,
                        choiceNames = list(
                          HTML('simple <br>probability'), 
                          HTML('decision <br>plot'), 
                          HTML('people <br>plot #1'),   
                          HTML('people <br>plot #2')),  
                        inline = TRUE)),
           uiOutput('gerdUI') #)
    ),
    column(6, (controls))
  ),
  (Odds_and_predictive_values) 
)

if(usingShinyApp) {
  shinyApp(ui = ui, server = server)
} else {
  server(input, output)
  ui
}

##' Using shinyApp, runjs works, but the app is in a scrollpane, and the JS console can't see the elements by ID.

```

